### ISSUE TITLE
Please add support for HUnit 1.3.0.0

### ISSUE THREAD

**Issue by peti** [haskell/test-framework#15]
http://packdeps.haskellers.com/feed?needle=test-framework-hunit

**Comment by hvr** [comment]
patches welcome :-)

**Comment by hvr** [comment]
A patch at #16 appeared!

**Comment by glguy** [comment]
I'm working on moving this along. I need to get upload permissions on hackage fixed up first.

**Comment by glguy** [comment]
Support added in version 0.3.0.2 as released to hackage
