### ISSUE TITLE
Support the latest QuickCheck

### ISSUE THREAD

**Issue by seagreen** [haskell/test-framework#21]
Current upper bound is `< 2.5`, current QuickCheck is 2.8.2.

**Comment by seagreen** [comment]
Oh, it looks like this repo contains both `test-framework-quickcheck` and `test-framework-quickcheck2`, the latter of which does allow the current version of QuickCheck. Is `test-framework-quickcheck` deprecated?

**Comment by hvr** [comment]
Where do you see `< 2.5` btw? it should have been `< 2` everywhere, as `test-framework-quickcheck` is for QuickCheck 1.x, whereas `test-framework-quickcheck2` is for QuickCheck 2.x

**Comment by seagreen** [comment]
Doh, I misread the error message. Thanks for the test-framework-quickcheck* explanation, that makes sense; feel free to close this.
