### ISSUE TITLE
Allow quickcheck 2.9

### ISSUE THREAD

**Issue by VictorDenisov** [haskell/test-framework#22]
Could you please relax restriction for quickcheck 2.9.
Test framework fails to build with the latest stackage build(which has quickcheck 2.9).
Subsequently it impacts bson driver: https://github.com/fpco/stackage/issues/1691

**Comment by glguy** [comment]
Fixed on hackage in 0.3.0.3

**Comment by chris-martin** [comment]
`test-framework-quickcheck` still requires `QuickCheck >= 1.1 && < 2`.

**Comment by chris-martin** [comment]
Oh nevermind, is that intentional? Are we to use `test-framework-quickcheck2` as its replacement? (see https://github.com/haskell/test-framework/pull/26)

**Comment by hvr** [comment]
@chris-martin yes, while I don't know why this was done this way (maybe it was to workaround some technical limitations in the tooling that aren't an issue anymore), `test-framework-quickcheck2` is supposed to be used for QuickCheck == 2.*

In the hopes to make this a bit more obvious, I just marked `test-framework-quickcheck` deprecated in favor of `test-framework-quickcheck2` on Hackage
