### ISSUE TITLE
Support for QuickCheck-2.11.3?

### ISSUE THREAD

**Issue by peti** [haskell/test-framework#35]
Support for `QuickCheck-2.11.3` would be extremely nice to have with regard to the upcoming GHC 8.4.x release.

**Comment by peti** [comment]
A few quick tests suggest that there is no effort involved in this task, actually, it's just a matter of relaxing the version constraint.

**Comment by hvr** [comment]
It's not merely a matter of checking whether it compiles but also reviewing the changelog when a major version bump is signalled. Have you checked at whether the changes in QC 2.11 are benign ?

**Comment by peti** [comment]
No, I didn't check that. I just observed that everything compiles and that users of `test-framework-quickcheck2` also compile and still succeed their test suites when building with QC 2.11.x.

**Comment by hvr** [comment]
Alright, I'll look into doing the due diligence

**Comment by hvr** [comment]
This will be revised on Hackage as real-soon-now when #37 turns green

**Comment by hvr** [comment]
@peti http://hackage.haskell.org/package/test-framework-quickcheck2-0.3.0.4/revisions/

**Comment by peti** [comment]
Thank you very much!
