### ISSUE TITLE
Bump ansi-terminal version upper bound 

### ISSUE THREAD

**Issue by L-TChen** [haskell/test-framework#49]
Just let you know that the latest version of `ansi-terminal` is 0.10. 

It does not seem that it introduces any breaking change, so it should be fine to bump up.

**Comment by RyanGlScott** [comment]
There is a PR at #46—it just needs someone to merge it.

**Comment by hvr** [comment]
For the record, the changes were

```
Version 0.10
------------

* Add support for setting the default color with new `SetDefaultColor`  constructor of the `SGR` type.
* `getTerminalSize` now flushes the `stdout` channel, to ensure the cursor  position is unaffected.
```

#46 got merged; and it's also been revised (see http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/)
