### ISSUE TITLE
Support GHC 8.8.1

### ISSUE THREAD

**Issue by asr** [haskell/test-framework#50]
I could install [test-framework 0.8.2.0](http://hackage.haskell.org/package/test-framework-0.8.2.0) with GHC 8.8.1 by running

```bash
$ cabal install test-framework --allow-newer=regex-posix
```

That is, I could install the library by using `regex-posix 0.96.0.0`. Could someone make the following revision in Hackage please

```
regex-posix (>=0.72 && <0.96) -> regex-posix (>=0.72 && <0.97)
```

Blocking https://github.com/agda/agda/issues/3725.

**Comment by hvr** [comment]
@asr Thanks for the reminder; I've reviewed the usage in `test-framework` to convince myself it is safe to extend compat to this new major version of `regex-posix` and revised according: http://hackage.haskell.org/package/test-framework-0.8.2.0/revisions/
