### ISSUE TITLE
Enable compilation with latest compiler and/or Stack environment

### ISSUE THREAD

**Issue by JoergBrueggmann** [haskell/test-framework#59]
To my best knowledge the "test-framework" cannot be build with the latest ghc compiler and/or Stack environment.

Background:
My plan was to receive sample data output from QuickCheck2. QuickCheck is capable to do so - but not QuickCheck2 - because the needed parameters cannot be passed. In order to achieve that I tried to modify QuickCheck2. Since, I work with The Haskell Stack and the newest environment - I got stuck.

Please, help

Code details:
https://github.com/JoergBrueggmann/Test6

**Comment by Bodigrim** [comment]
Why would not you migrate to `tasty`? `test-framework` has been on life supports for ages.

**Comment by Bodigrim** [comment]
FWIW `test-framework` compiles just fine with GHC 8.10. But you are not supposed to copy-paste source tree into your package, declare it as `build-depends` in your Cabal file.

**Comment by JoergBrueggmann** [comment]
Thank you Bodigrim. I appreciate all your advice.

So, I will have a closer look at tasty. The first glimpse to convinced me.

Regarding your second comment: I am keen to fully understand. I even would pay for it, if you would enable me to set up the copied sources in the Haskell Stack environment, would you?

Background:
I am using The Haskell Stack which generates the cabal-file "automatically" from the project setup and in particular from the file `package.yaml`. The generated cabal file contains three time `build-depends` (below library, executable, and test-suite).

**Comment by Bodigrim** [comment]
> Regarding your second comment: I am keen to fully understand. I even would pay for it, if you would enable me to set up the copied sources in the Haskell Stack environment, would you?

@JoergBrueggmann if https://github.com/JoergBrueggmann/Test6/pull/1 is to your liking, please consider donating to Haskell Foundation: https://haskell.foundation/donations/

**Comment by JoergBrueggmann** [comment]
@Bodigrim: Thank you for your effort. You must be Andrew, don't you? I just donated 50$, and to gain some more help.

However, there seem to be a missunderstanding. By "copied sources" in "...if you would enable me to set up the copied sources in the Haskell Stack environment..." I mean: To use the source files of the test-framework to be able to modify them in a Stack environment. You just deleted them. It should be possible to keep the files without just importing them, isn't it? If I would keep the files I would be able to understand its resictions an could even propose an improvement.

If you see a way to setup the project in my stack environment than I would be very greatful.

Thanks again.

**Comment by Bodigrim** [comment]
@JoergBrueggmann in this case, when you are in `Test6` folder, run `stack unpack test-framework`. It will create `test-framework-0.8.2.0` folder, containing a local `test-framework` package, which you can refer from `stack.yaml`:
```yaml
resolver: lts-18.24
packages:
- .
- test-framework-0.8.2.0
```
Now `stack test Test6` will build tests against whichever sources for `test-framework` are available in a local dir. 

----

However, if you run `stack test`, which tries to run tests for all local packages, including `test-framework` itself, you'll get 
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for test-framework-0.8.2.0:
    libxml must match >=0.1.1, but the stack configuration has no specified version  (latest matching
           version is 0.1.1)
needed since test-framework is a build target.

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps
    in /Users/andrew/programs/Test6/stack.yaml:

- libxml-0.1.1@sha256:aa167fb817ef2d0a87e7ee64452939491cc151472e1150ced0e89dc954c4874e,922

Plan construction failed.
```

Indeed, you can edit `stack.yaml` appropriately and rerun `stack test`:
```yaml
resolver: lts-18.24
packages:
- .
- test-framework-0.8.2.0
extra-deps:
- libxml-0.1.1
```

Unfortunately, this will fail with 
```
test-framework            > /Users/andrew/programs/Test6/test-framework-0.8.2.0/Test/Framework/Tests.hs:13:18: error:
test-framework            >     Not in scope: ‘TP.tests’
test-framework            >     Module ‘Test.Framework.Runners.ThreadPool’ does not export ‘tests’.
test-framework            >    |
test-framework            > 13 |         TestList TP.tests,
test-framework            >    |                  ^^^^^^^^
test-framework            >
test-framework            > /Users/andrew/programs/Test6/test-framework-0.8.2.0/Test/Framework/Tests.hs:14:9: error:
test-framework            >     Not in scope: ‘XT.test’
test-framework            >     Module ‘Test.Framework.Runners.XML’ does not export ‘test’.
test-framework            >    |
test-framework            > 14 |         XT.test
test-framework            >    |         ^^^^^^^
test-framework            >
test-framework            > /Users/andrew/programs/Test6/test-framework-0.8.2.0/Test/Framework/Tests.hs:16:16: error:
test-framework            >     Not in scope: ‘XT.property’
test-framework            >     Module ‘Test.Framework.Runners.XML’ does not export ‘property’.
test-framework            >    |
test-framework            > 16 |     quickCheck XT.property
test-framework            >    |                ^^^^^^^^^^^
test-framework            >
```

This is a genuine failure: while `test-framework` library itself is buildable, its test suite is not. As I said, `test-framework` has been on life support for many-many years and only library has been maintained. All new users should migrate to `tasty`.

**Comment by JoergBrueggmann** [comment]
This is unfortune, but OK! The magic keyword of stack is `unpack`, which I was looking for. I will give `tasty` a try.

Thank you, @Bodigrim.
