### ISSUE TITLE
New release upload needed for GHC HEAD/7.10 

### ISSUE THREAD

**Issue by hvr** [haskell/test-framework#7]
Currently `test-framework-0.8.0.3` does not build with GHC HEAD due to a missing `Applicative` instance (which was added as per 0dac7f3611546f424929d24e4d0899e8f430a841)

Current `master` builds w/ GHC HEAD though; moreover, all previously uploaded `test-framework` packages need their cabal file edited to constrain `base <4.8` as they're now known to be incompatible w/ `base-4.8`

**Comment by bos** [comment]
I definitely don't want to maintain this, that's why it's under the haskell org and not me.
